follow_symlinks = false
add_newline = false
format = """
$username\
$hostname\
$localip\
$shlvl\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$status\
$cmd_duration\
$fill\
$sudo\
$time
$character\
"""

[directory]
truncation_symbol = ".../"
style = "green"

[git_branch]
style = "blue"

[git_commit]
style = "blue bold"
tag_disabled = false

[git_status]
format = "$all_status$ahead_behind"
conflicted = '[${count} ](red bold)'
stashed = '[${count} ](green)'
deleted = '[${count} ](red)'
renamed = '[󱀱${count} ](blue)'
modified = '[${count} ](yellow)'
staged = '[${count} ](blue)'
untracked = '[${count} ](blue)'
ahead = ' ⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'

[status]
disabled = false
format = '[$status $symbol ]($style)'
symbol = "X"
success_symbol = ""
success_style = "green bold"

[fill]
symbol = " "

[sudo]
disabled = false
format = ' '

[time]
disabled = false
format = '$time '
